package dogs.domain.value_object

enum class TemperamentValue {
    DOCILE, STUBBORN, CHARMING, CLEVER, SOCIABLE, PLAYFUL, QUIET, ATTENTIVE, SELF_ASSURED, OBEDIENT, FEARLESS,
    STEADY, GOOD_NATURED, DEVOTED, ALERT, COURAGEOUS, EASYGOING, AFFECTIONATE, ACTIVE, INTELLIGENT, CURIOUS,
    LOYAL, INDEPENDENT, ATHLETIC, PATIENT;

}